networks:
  default:
    external: {name: host}
services:
  node1:
    deploy:
      mode: replicated
      placement:
        constraints: [node.id == h8wq4b2uy6fiac37lbx16gb08]
      replicas: 1
    environment: {WASM_SERVERLESS_NODEID: 1}
    image: wasm_serverless:v1
    ports:
    - {mode: host, published: 2500, target: 2500}
    - {mode: host, published: 2501, target: 2501}
    volumes: ['/etc/wasm_serverless/config:/etc/wasm_serverless/config']
  node2:
    deploy:
      mode: replicated
      placement:
        constraints: [node.id == h8wq4b2uy6fiac37lbx16gb08]
      replicas: 1
    environment: {WASM_SERVERLESS_NODEID: 2}
    image: wasm_serverless:v1
    ports:
    - {mode: host, published: 2505, target: 2505}
    - {mode: host, published: 2506, target: 2506}
    volumes: ['/etc/wasm_serverless/config:/etc/wasm_serverless/config']
  node3:
    deploy:
      mode: replicated
      placement:
        constraints: [node.id == t8f80nn3qxavell7leopbab40]
      replicas: 1
    environment: {WASM_SERVERLESS_NODEID: 3}
    image: wasm_serverless:v1
    ports:
    - {mode: host, published: 2510, target: 2510}
    - {mode: host, published: 2511, target: 2511}
    volumes: ['/etc/wasm_serverless/config:/etc/wasm_serverless/config']
  node4:
    deploy:
      mode: replicated
      placement:
        constraints: [node.id == t8f80nn3qxavell7leopbab40]
      replicas: 1
    environment: {WASM_SERVERLESS_NODEID: 4}
    image: wasm_serverless:v1
    ports:
    - {mode: host, published: 2515, target: 2515}
    - {mode: host, published: 2516, target: 2516}
    volumes: ['/etc/wasm_serverless/config:/etc/wasm_serverless/config']
  node5:
    deploy:
      mode: replicated
      placement:
        constraints: [node.id == d8huj03dv09keg3gp4vh1cj7k]
      replicas: 1
    environment: {WASM_SERVERLESS_NODEID: 5}
    image: wasm_serverless:v1
    ports:
    - {mode: host, published: 2520, target: 2520}
    - {mode: host, published: 2521, target: 2521}
    volumes: ['/etc/wasm_serverless/config:/etc/wasm_serverless/config']
  node6:
    deploy:
      mode: replicated
      placement:
        constraints: [node.id == d8huj03dv09keg3gp4vh1cj7k]
      replicas: 1
    environment: {WASM_SERVERLESS_NODEID: 6}
    image: wasm_serverless:v1
    ports:
    - {mode: host, published: 2525, target: 2525}
    - {mode: host, published: 2526, target: 2526}
    volumes: ['/etc/wasm_serverless/config:/etc/wasm_serverless/config']
version: '3.5'
