name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Ansible
      run: sudo apt install python3 python3-pip && bash scripts/install/install_ansible.sh
    - name: Setup Ansible
      run: bash scripts/deploy_single_node/1.ansible_setup.sh
    - name: Ansible install all
      run: ansible-playbook -vvv scripts/install/ans_install_build.yml
      
    - name: Build release
      run: ansible-playbook -vvv scripts/build/ans_build_release.yml
    
    - name: Build WasmEdge Image
      run: bash docker/WasmEdge/build_image.sh
    - name: Build WasmServerless Image
      run: bash docker/WasmServerless/build_image.sh
    
    - name: CI
      run: bash scripts/deploy_single_node/ci.sh
